### ISSUE TITLE
Provisional Governance Council Nominations

### ISSUE THREAD

**Issue by Dev-JamesR** [Ether1Project/Governance#2]
**Contact Info**
Discord username and an alternate method of contact should be listed here.

**Ether-1 Community History**
Describe your history with the Ether-1 Project

**Platform Summary**
Summarize your platform here.

**Platform Details**
Outline the details of your platform and where you see the project heading.

**Comment by Goose-Tech** [comment]
**Contact Info**
(Discord) °☆ Goose [UTC -4]#5820
(e-mail) goose@goosetech.pro

**Ether-1 Community History**
I have been following Ether-1 for over 1 year now. I have a small YouTube channel focused on technology and cryptocurrency where I have made several videos in support of the Ether-1 vision and the project's goal of providing webhosting through the use of smart contracts and IPFS storage. At a time when censorship is becoming an almost constant threat, I believe that a decentralized solution such as IPFS will help pave the path to a free sharing of information and ideas, which is what the internet has been designed to do.

**Platform Summary**
- Bring awareness to the project by promoting the Ether-1 project on YouTube and other social media outlets
- Assist the Ether-1 team in realizing the goal to #DecentralizeEverything
- Find altruistic ways in which the technology being built may give people a means to freely share their ideas

**Platform Details**
One of the challenges any upstart faces is getting others excited about what they are doing. The Ether-1 team has done a phenomenal job of not only forking a highly popular cryptocurrency (Ethereum), but has improved upon it to give it added significance. Smart contracts are one of the most significant innovations in the blockchain space besides Bitcoin; to put smart contracts to use as the backbone for websites takes hosting to a whole other level of autonomy. In the future, there will be no need for centralized webhosting providers. All users will have to do is get some ETHO and host their own content on a fully decentralized IPFS storage network made possible by smart contracts. 

While IPFS storage is the most decentralized solution for websites and sharing content, there are drawbacks, e.g. uploaded files cannot be changed or modified, so mistakes or updates will be difficult to manage. There are no tools to help users develop their own website, or templates to give them the ability to more easily create a site and upload it to ethoFS. Also, the network currently has a limited amount of space, and the fee to upload is cost prohibitive for large files (such as videos). We need solutions to these problems.

At this stage in project development I would propose the following:
1a. A re-evaluation of the block reward fee to incentivize node owners more than miners (this will encourage more people to create nodes, which will help mitigate a lack of storage space)
1b. A re-evaluation of the minimum specifications for different node tiers could also help mitigate the amount of storage space
2. A re-evaluation of the fee charged to store files on ethoFS (unless the charges to upload are comparable to offerings from other hosting companies, ethoFS will have priced itself out of the market)
3. Promote the development of a DropBox type app that will allow the use ethoFS storage space for private, encrypted, P2P file sharing (users upload content, give it a password, then share the link/password with others to access it)
4. Encourage the development of a second method of storing websites (e.g. IPNS) as an option for users to rent storage space on the ethoFS network, which this will allow for dynamic content and easy updates. An IPNS option would be in addition to the IPFS system that is already in place, and the two file systems should work together depending on how the smart contract is executed, e.g. website is stored in IPNS space, but refers to static content that is stored in IPFS space
5. Create more video and audio (podcast) content to build awareness to the Ether-1 project and the phenomenal work that has already been accomplished (the project is beyond proof-of-concept, it's time to build use cases)
6. Coordinate with other team and community members to focus time, talent, and energy accordingly to bring about the aforementioned goals

**Comment by pistol22cal** [comment]
Contact Info:

Discord: @pistol22cal#7602 | Pistol of $ETHO since May'18 | ID: <378374529707278347>
email: admin@pistolcrypt.com

Ether-1 Community History
Hi, I am Pistol! I have been in the ETHO community since the beginning.

Platform Summary
• Focus on marketing
• Develop our own mining algo and software
• Decentralize Everything

Platform Details
We 1000% need to market what we have; we have a valid working product and supply a valuable service. People do not even know we exist, and I want to change this and now!
I want to be the voice for the little guy, the guy that has 1 GPU and wants to be a part of this whole thing we call crypto. I want ETHO to be the coin he wants to mine, and I want him to be profitable! I want node owners to be satisfied with their earnings and to be able to have a direct say in the direction that ETHO takes. Node owners are our investors, period, and as such should have a say in every aspect of the project’s development.
I believe we should develop our own mining algorithm and have our own miner software. It should be equally good on AMD and Nvidia. We should be ASIC resistant as well as FPGA resistant. This would be a big deal and allow us to move away from the crowd, allowing us to be minable on almost any modern GPU. DAG file size is an issue and if we can remove this limitation, we can have a nice future in mining.
I believe the monetary policy in its current form is fair to all and I would welcome changes if a fair and balanced policy could be achieved.
Rebranding is of little concern to me and I will not focus much effort into this area as I feel it is not a main concern currently.
Finally, full decentralization is my focus for Ether-1 we need the tools Xerom is testing moved to Ether-1 ASAP once fully tested.

**Comment by Crypto-Saiyan** [comment]
Contact Info:

Discord: @Crypto_Saiyan of $ETHO Aug’18#9653
email: cryptosaiyan1@gmail.com

**Ether-1 Community History**:

I have been following **Ether-1** since August 2018,mining,setting up Nodes,been part of the Community & helping where i can in Discord.
I believe in the idea of #DecentralizeEverything and I want to make it come true with **Ether-1/Xerom**.

**Platform Summary**:

• Focus on marketing
• Change Node Collateral
• Rebrand project to attract more people
• Realizing our goal to #DecentralizeEverything!

**Platform Details**:

We have a great working product & need to focus more on Marketing,get more Exposure.

I think we need to change the **Node Collateral** to get more Nodes Online on the network to help grow **ethoFS**.

**Example**:

**SN**: 5,000 ETHO
**MN**: 10,000 ETHO
**GN**: 20,000 ETHO

This way we would get more **Nodes** running with more space available for the **ethoFS** with no need to change the rewards while the **Node ROI** would be faster.

Monetary policy in its current state is fair to all & should remain as is.

Rebrand the project in order to move away from the name which is too similar to **Ethereum**,but it is not a main concern currently & should be done later on in 2020.

Implementing **Decentralized Node Protocol** to ETHO Nodes once fully tested.

**Comment by hashratez** [comment]
**Contact InfoContact Info**
Discord: HashRatez#1904
Email: chris@ether1.org

**Ether-1 Community History**
Active full-time efforts since Summer 2019

**Platform Summary**
Facilitating broad adoption of the Ether1 platform outside the crypto-space.

**Platform Details**
There is a huge gap between the real world and the crypto world.  For Ether1 to be truly successful the project must navigate its way to functionality that appeals to local pizza shop down the street as well as Fortune 500 companies.  Only then will ETHO be worth more than 100 Satoshi.  At this point "Decentralize Everything" has little, if any, meaning to humanity.  HOWEVER every single day as more and more personal restrictions are instituted, further degradation of privacy, centralized monetization of the individual all bring awareness to the ultimate benefit the Ether1.  

But this is a long road....

My efforts are to help provide insights and direction from the marketplace to guide Ether1 now and in the future.  If we don't live through today there will be no tomorrow.

While I run nodes, mine and do other crypto activities my role on the Provisional Leadership Council would be much more business orientated/focused.  For example; setting long term goals, establishing budgets and most importantly expectations based on reality.  You may not like to hear what I have to say, but at least you will hear it.  On the flip side, I do pride myself on the ability to listen and change positions based on better ideas/arguments from others.

**Comment by Dev-JamesR** [comment]
> Contact Info:
> 
> Discord: @Crypto_Saiyan of $ETHO Aug’18#9653
> email: [cryptosaiyan1@gmail.com](mailto:cryptosaiyan1@gmail.com)
> 
> **Ether-1 Community History**:
> 
> I have been following **Ether-1** since August 2018,mining,setting up Nodes,been part of the Community & helping where i can in Discord.
> I believe in the idea of #DecentralizeEverything and I want to make it come true with **Ether-1/Xerom**.
> 
> **Platform Summary**:
> 
> • Focus on marketing
> • Change Node Collateral
> • Rebrand project to attract more people
> • Realizing our goal to #DecentralizeEverything!
> 
> **Platform Details**:
> 
> We have a great working product & need to focus more on Marketing,get more Exposure.
> 
> I think we need to change the **Node Collateral** to get more Nodes Online on the network to help grow **ethoFS**.
> 
> **Example**:
> 
> **SN**: 5,000 ETHO
> **MN**: 10,000 ETHO
> **GN**: 20,000 ETHO
> 
> This way we would get more **Nodes** running with more space available for the **ethoFS** with no need to change the rewards while the **Node ROI** would be faster.
> 
> Monetary policy in its current state is fair to all & should remain as is.
> 
> Rebrand the project in order to move away from the name which is too similar to **Ethereum**,but it is not a main concern currently & should be done later on in 2020.
> 
> Implementing **Decentralized Node Protocol** to ETHO Nodes once fully tested.

I am curious about your approach to node rewards/policy/requirements. I agree that we need to encourage more nodes to come online but from a historical look at how nodes have been deployed they tend to move toward an equilibrium point. If we lower collateral requirements but leave rewards alone, more nodes will come online and push the ROI to where we started. So this will accomplish the original goal of more nodes but ROI will move back to its equilibrium point. A reward adjustment in tandem with collateral adjustment might be a the way to go. Since we value and need nodes in our decentralization effort maybe a 50/50 reward split between miners and nodes would further help this.

**Comment by Crypto-Saiyan** [comment]
Yes we would need to look at how to best adjust the rewards,50/50 would be good like you said.

**Comment by Crypto-Saiyan** [comment]
> I am curious about your approach to node rewards/policy/requirements. I agree that we need to encourage more nodes to come online but from a historical look at how nodes have been deployed they tend to move toward an equilibrium point. If we lower collateral requirements but leave rewards alone, more nodes will come online and push the ROI to where we started. So this will accomplish the original goal of more nodes but ROI will move back to its equilibrium point. A reward adjustment in tandem with collateral adjustment might be a the way to go. Since we value and need nodes in our decentralization effort maybe a 50/50 reward split between miners and nodes would further help this.

Yes we would need to look at how to best adjust the rewards,50/50 would be good.
So if it would be changed to 50/50,lets say at Block 4M it would be 3 coins for Miners & 3 coins for Node Owners.

**Comment by TegoCryptoman** [comment]
.
Contact Info:

-> Discord: TegoCryptoman#8180
-> Telegram: @TegoCryptoman
-> Twitter: @TegoCryptoman
-> Mail: schz.ernest@gmail.com

.
Ether-1 Community History:

My history in Ether-1 is very short, I've only been part of the guild for a few months, however my stay as part of ETHO has been interesting.

Parallel to all this, your technology is of much interest, since the vision of ETHO & XERO (your alternate chain), are a project that make a quite promising digital era, with a focus on improving the Internet of things.

.
Platform Summary & Platform Details:

At this point, I declare my direct involvement with ETHO & XERO.

*Tego's Charity - Social Activity
I promote Tego's Charity, is a project in the social field where ETHO & XERO are part of that we can do great things for the most underprivileged and thus build a better world, because I firmly believe that by every act of kindness we rejoice the soul of others.

*Trade P2P
Also, I carry out financial activities in order to achieve the basic principles and foundations of digital currencies, such as the marketing of both ETHO & XERO in the payment of goods and services in a P2P way.

*I'm Tego
One of my favorite approaches is to be able to shout everywhere and to the world the fact that I am carrying out an important work, personally I move away from anonymity and I show myself to the community so that they know that I am real and that together we are betting on this, on what I do, and we do.

*Hispanic Community
On the other hand, since I am a native of Venezuela, I seek to promote the Spanish-speaking community at ETHO & XERO. In this way, I will be serving as an ambassador in Spanish, offering all the support and assistance you desire for those who are there and for those who arrive. Together we are more.

**Comment by Bigpiggy01** [comment]
Contact Info:

Discord: @443443175802273833 or @Bigpiggy01#9922
email: asshatsupremo@gmail.com

Ether-1 Community History:

Not much, I hopped on a couple of months back. Mainly due to Goose being onboard and really liked what saw and have seen so far.

I have however been in crypto for a very long time since early 2011 and have seen a fair bit come and go.

I'd be willing to run for the governance council. I am happily contrarian, I detest anything that centralizes in any way and I have a pet hate for hidden agendas/ scams by omission. 

Should I end up on the governance council, I will use my position to push old school crypto values every chance I am given. As well as use my extensive network of connections in Asia to get the project the traction there that is still badly needed.

**Comment by W-Bell** [comment]
Contact Info
Spooky guy on phone
wesbell78@gmail.com

Ether-1 Community History
I am a miner. My farm mines at roughly 200mh.
Discovered it when I began to look into the ETH chains more. 

Platform Summary
 I lack coding skills. However, I see it is vital to enable this to be friendly to non tech savvy people so that the idea of decentralizing everything will in fact be possible. Here are a few ideas I have but myself have no capability of providing but getting it into the ether will matter
-support a purchase pass through where people can purchase ETH/BTC and use it directly to purchase hosting.
-advocate for a simple user GUI that would allow people an ease of use and more importantly would provide an entry level use case for the function.
-private side chains that are PoS through the already existing ethoFS system. These could be targetted as chains for specific businesses who wish to have their own chains. They could be entirely secretive to protect the identity of the businesses using them and to also ensure the chain only collects the data that they themselves wish to hold and store within their own chain. The side chain would pay into the ethoFS just like a regular usage of the chain would be expected, once again making an anonymous side chain possible but yet still having the decentralized option available. 


Platform Details
In order to decentralize everything, even I, a brainlet, must be able to use it.

**Comment by dylie** [comment]
**Contact Info**

- Discord: Dylie#8480
- E-mail: djfarock@gmail.com
- Twitter: twitter.com/CryptoDylie
- Github: @dylie 

**Ether-1 Community History**

Hello my fellow etho'rs. My name is Dylan, better known as Dylie.

I've been lurking around in the ether-1 discord since December 2018. My first real job done for ether-1 was somewhere in january, I was asked to perform some gfx designs for Ethan and James. Great succes! After my first real job for ether-1 Fallen and I gave birth to http://ethofuse.net/ , better known as the #HODLgame. This little game as I like to call it was one of the first Dapps smartcontract made on the ether-1 blockchain. _For more info, visit the website._

Further on I've successfully performed an upgrade on the ether-1 discord bot from that time. Since  March ETHO Master (bot) rules the discord and protects you from spammers/scammers that try to join our discord. Shortly after that I was fully hired as an ether-1 developer and gfx designer. You may also know me from the sweet tipping bot I've created. I'm sure you already used it ;).

Ofcourse there is more, like http://uptime.ether1.org/ which is an handy tool you can use to check the majority of the uptimes on every ether-1 platform, but this you might already know.

_Beside all my previous work, I am still active and developing new tools and software working side by side with Fallen (Ethan) and James. Working hard to #Decentralize EVERYTHING._

**Platform Summary**

> Marketing focus
> Network expansion by getting miners to switch to nodes
> Decentralize everything -> Decantralized Exchange (DEX)

**Platform Details:**

In these stages ether-1 is in right now we need to push our marketing to the limits. For example, the current youtube crypto drama, this is a PERFECT opportunity to reach out to all of the striked youtubers and provide them a safe and secure, but mostly DECENTRALIZED backup. I would invest a part of the dev fundings into providing the storage cost for these backups. 

Beside that, we need to expand our node network day by day. Get current miners to switch over to nodes and help the network grow. I think we made the first step of doing that by implementing KRONOS succefully. The KRONOS update + the current staking platform where people with to small of etho holdings also have a chance to get their own node running and provide their piece of help towards the growth of the network. This, in my eyes is a great step for ether-1 to also move on to the real use case. http://data.ethofs.com/ipfs/QmcTA2Hyq1KdCp8xMVffjGY3K2yKaHtiNs2FP1euRcMcCb

Last but not least, getting ether-1 on a decent DEX would also help the project alot towards the 100% decentralization mark.

Kind regards, 

your friendly neighborhoud dev Dylie. http://data.ethofs.com/ipfs/QmckYpz6hsMN2tDP6WCaPQEzfF61nJV49LuEHiSqh5SSMx

**Comment by Caparino** [comment]
**Contact Info**
--------------------------------------------------------------------------------------------------------
Discord: Cap#7089
Email: cap@ether1.org


**Ether-1 Community History**
--------------------------------------------------------------------------------------------------------
My name is Cap, and I was brought on the Ether-1 team as the Head of Marketing. 

My skill set comes from experience gained by working with projects in many decision making roles--not only in the cryptocurrency industry, but also with educational and engineering organizations--to successfully create industry awareness and user growth, as well as improving the overall organizational structure. I think my experience will heavily promote my efficacy as a council member.

**Platform Summary**
--------------------------------------------------------------------------------------------------------
1) Represent The People's Voice
2) Decentralize Everything, Within Reason
3) Create an ecosystem that educates participants and incentivizes them to vote, create content, and participate in the Ether-1 economy
4) Account for Holders with every decision

**Platform Details**
--------------------------------------------------------------------------------------------------------
1) Many of our ideas come from discussing with others. I often have discussions and ask others about the problems and solutions of today, and have a much better understanding of all standpoints by the end of it. This process allows for all ideas to go through the gauntlet and only the best ones survive at the end. If elected, I would like to create a place that ideas can be discussed by everyone, for everyone. This will be a great resource and communication hub for council members to see the views of, and stay in touch with, every participant of the Ether-1 ecosystem.

2) Decentralizing is what we're aiming for, but it should be implemented where it makes sense. I want to push the envelope to see how much we can decentralize without introducing unnecessary redundancy or fixing something that isn't broken. Can the governance council be decentralized? Can that decentralization be decentralized? Would aforementioned decentralization actually solve a problem or prevent a future one or is it only for the sake of decentralization? Questions like this will and must be brought up for sensible policy implementation to take place

3) For true decentralization to work well, everyone has to know the facts and be able to think logically whether a decision is for the general good. A large part of governments not working for the people today is an uninformed (or misinformed) and uninterested population. How do we provide conditions for true decentralization without forcing people to participate in the steps to being able to do those things? Creating conditions where everyone is incentivized to have a good understanding of the facts is the end goal--we just need to figure out how we get there.

4) I want the best financial outcome for every person that holds ETHO. Any effects on Ether-1's coin price will be considered heavily whenever I introduce or vote on a council measure.

Thank you for reading. If elected, I will do my best to serve you well.

**Comment by Primate411** [comment]
**Contact Info**
(Discord) @Primate of $ETHO#1111 
(e-mail) admin@ether1.cloud

**Ether-1 Community History**
I have been with ether-1 since the end of 2018. I have gotten involved with all possible levels of the project including standing up a documentation portal ([docs.ether1.org](https://docs.ether1.org)), helping with user support, writing social media posts, interacting with outside services. I worked my way up to a project management position and now it the time to step down in order to build my own ether-1 enclave and #DecentralizeEverything

**Platform Summary**
- Stand up ether1.cloud website and other social media services to help decentralize this aspect of the project
- Provide ENS support for the ether-1 blockchain so you can tip me at primate.etho
- Make sure things are fair for node operators, the lifeblood of the project but also for miners and all other contributors
- Support the goal of #DecentralizeEverything by supporting actions which will help get us there.
- Make sure fair & robust governance is put in place

**Platform Details**
I will form a separate social media and website presence for the project in order to decentralize the publishing of information about the project. This includes a separate twitter account and website in the ether1.cloud domain.  I will grow another Discord server as well as Telegram server.  
In March 2020 I will start working on implementing the Ethereum Naming System into ether-1 and spearhead the effort to include it in the web wallet and the desktop wallet for easy payments.
I will help make sure fair governance is put in place that works for everyone, including node operators.  For node operators I will fight to have them represented as a 2nd voting body in addition to the council members. I will keep track of work being done on the founding document of the ether-1 project along with anyone else who wants to get involved in the effort.

**Comment by qbvbsite** [comment]
Contact Info
Discord username: @CableGod
Email: james@pcmods.ca

Ether-1 Community History
Been a member of ETHO for over a year and a half contributing in discussions how topics such as governance, re-branding, dApp development, and ETHOLab. Due to RL getting in the way I have been somewhat inactive for the past six month but things have started to die down now so I can devote some time to ETHO. I have also been in cypto off/on for 4 years and with the past 2 somewhat focus on application development.

Platform Summary
Heavy focus on governance, decentralization, and dApp development

Platform Details
ETHO has been making great strides in decentralization and governance of ETHO over the past year. I would like to continue to flourish in 2020 and if I was on council would ensure Governance becomes a success and doesn't go the waste side. To keep things going I would like to see a bi-monthly/monthly round table where the community can bring issues up to the council in an official manner which then can be voted on and actioned. 

As many of you know I'm also very passionate about ETHO needing strong dApp development. I would like to see a dedicated dApp development team created which can focus on application important to ETHO. By having a dedicated team of dApp developers projects will have a better chance of successfully getting off the ground and not die off when RL gets in the way. I very much believe that quality dApp's will help get the word out about ETHO and bring it to the forefront.

**Comment by regkgb1** [comment]
Contact Info
discord : theekgb#1877
telegram : https://t.me/theeonlykgb

Ether-1 Community History
I do not have a history here really.  Just joined in December 2019.  Have already come to appreciate the vision and energy of the community. With alot of great ideas already brewing.

Platform Summary
Decentralization. community, advocacy.

Platform Details
I am new here in ether-1.  This would be the first project I have attempted this level of involvement.  I have been following, using, researching blockchain technologies for a few years.  I am a strong advocate and supporter of decentralization.  It is extremely important to many facets of society.  There are alot of already great ideas by several candidates for council already.  My platform is pretty simple.  I am strong with working with team, technology, and architecture.  I would always be advocating and holding to the idea of decentralization of everything.  Fair representation of all groups involved.  Assisting with the placement of the future governance of the project.  Also learning new ways and skills to be further involved in parts of the project.  I want to learn and help anyway I can, while helping with the future of ether-1!  Thank you for the consideration and opportunity.  Look forward to what the community decides!

**Comment by hashratez** [comment]
> Contact Info
> Discord username: @Cablegod
> Email: [james@pcmods.ca](mailto:james@pcmods.ca)
> 
> Ether-1 Community History
> Been a member of ETHO for over a year and a half contributing in discussions how topics such as governance, re-branding, dApp development, and ETHOLab. Due to RL getting in the way I have been somewhat inactive for the past six month but things have started to die down now so I can devote some time to ETHO. I have also been in cypto off/on for 4 years and with the past 2 somewhat focus on application development.
> 
> Platform Summary
> Heavy focus on governance, decentralization, and dApp development
> 
> Platform Details
> ETHO has been making great strides in decentralization and governance of ETHO over the past year. I would like to continue to flourish in 2020 and if I was on council would ensure Governance becomes a success and doesn't go the waste side. To keep things going I would like to see a bi-monthly/monthly round table where the community can bring issues up to the council in an official manner which then can be voted on and actioned.
> 
> As many of you know I'm also very passionate about ETHO needing strong dApp development. I would like to see a dedicated dApp development team created which can focus on application important to ETHO. By having a dedicated team of dApp developers projects will have a better chance of successfully getting off the ground and not die off when RL gets in the way. I very much believe that quality dApp's will help get the word out about ETHO and bring it to the forefront.

I really like the fact you are opening to monthly meetings (for me bi-weekly even if possible) the biggest issue facing Ether1 is the lack of communications.  This simple concept is vital for young projects.  You've got my vote!

**Comment by Primate411** [comment]
The Ether-1 provisional council has been elected: https://github.com/Ether1Project/ECPs
