### ISSUE TITLE
Provisional Councilman @Goose-Tech Replacement

### ISSUE THREAD

**Issue by Primate411** [Ether1Project/Governance#3]
The Ether-1 Project is holding an election to choose 1 council person to replace @goose-tech who tendered his resignation this week.  The nomination process will go on for 7 days, followed by 7 days of voting in the Ether-1 Discord.

**Timeline**
March 1st - March 8th: Self-nominations in this thread.
March 8th - March 15th: Voting in the [Official Ether-1 Discord](https://discordapp.com/invite/MFn9Tmz)

---

Fill out your council person application below by responding to this post. Make sure to include the info below highlighted in black as a minimum necessary amount of info to be entered into election.

Example nominations can be found on: [https://github.com/Ether1Project/Governance/issues/2](https://github.com/Ether1Project/Governance/issues/2)

---

**Contact Info**
Discord username and an alternate method of contact should be listed here.

**Ether-1 Community History**
Describe your history with the Ether-1 Project. What does Ether-1 mean to you?

**Platform Summary**
Summarize your platform here. Bullet points on how you want to see the project change and/or improve.

**Platform Details**
Outline the details of your platform with details/steps on how to get from where we are now to where we are going, according to your vision.

**Ether-1 Council Wallet Address**
Your ETHO council wallet.  To be used on the Council Multisig wallet.  Make sure to have a good backup of this wallet.

**Comment by Crypto-Saiyan** [comment]
Contact Info:

Discord: @Crypto_Saiyan of $ETHO Aug’18#9653
email: cryptosaiyan1@gmail.com

Ether-1 Community History:

I have been following Ether-1 since August 2018,mining,setting up Nodes,been part of the Community & helping where i can in Discord,written Node setup guide for Unit Frontier,helped others setting up Nodes & wallets,etc...

I believe in the idea of #DecentralizeEverything and I want to make it come true with Ether-1/Xerom.


Platform Summary:

• Focus on marketing
• Change Node Collateral
• Get miners to switch over to Nodes/Staking
• Rebrand project to attract more people
• Realizing our goal to #DecentralizeEverything!

Platform Details:

We have a great working product & need to focus more on Marketing,get more Exposure.

I think we need to change the Node Collateral to get more Nodes Online on the network to help grow ethoFS.

Example:

SN: 5,000 ETHO
MN: 10,000 ETHO
GN: 20,000 ETHO

This way we would get more Nodes running with more space available for the ethoFS.

We need to expand our node network,hit 1000+ Nodes by the end of 2020.
Also we need to get current "Miners" & all "ETHO Hodlers" to switch over to "Nodes" and help the network grow before we move to POS,what would be the case in the future.

People can run their Own Nodes if they have the Collateral or borrow it via our Staking service,even lend the extra coins to earn some more ETHO.

Rebrand the project in order to move away from the name which is too similar to Ethereum,but it is not a main concern currently & should be done later on in 2020/2021.

Implementing Decentralized Node Protocol to ETHO Nodes once fully tested & ready.


Ether-1 Council Wallet Address:  0xE1Fe94c4B9B697Fe773534A79A301FA4f186e5Ff
